config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'donations/new'
  get 'donations/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'categories#index'

  resources :categories do
    resources :articles do
      resources :comments
    end
  end

  resources :donations, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  validates :category, presence: true


  def self.recent_articles(limit = 5)
    order(created_at: :desc).limit(limit)
  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :destroy

    validates :name, presence: true, uniqueness: true

    def total_articles
        articles.count
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
  belongs_to :user
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived]

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :first_name, :last_name, :user_name, presence: true

  def user_comments
    comments
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
      
    protected
      
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_name])
    end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true
class ArticlesController < ApplicationController


  before_action :set_category
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = @category.articles
    @recent_articles = Article.recent_articles
  end

  def show
    # @article = Article.find(params[:id])
  
  end

  def new
    # @article = Article.new
    @article = @category.articles.build
  end

  def create
    # @article = Article.new(article_params)

    # if @article.save
    #   redirect_to @article
    # else
    #   render :new, status: :unprocessable_entity
    # end
    @article = @category.articles.build(article_params)
    if @article.save
      redirect_to category_article_path(@category, @article), notice: 'Article was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])

    # if @article.update(article_params)
    #   redirect_to @article
    # else
    #   render :edit, status: :unprocessable_entity
    # end
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to category_article_path(@category, @article), notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    # redirect_to root_path, status: :see_other

    @article.destroy
    redirect_to category_articles_path(@category), notice: 'Article was successfully destroyed.'    
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :status, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :destroy, :update]
    
    def index
      @categories = Category.all
      
      @total_articles_per_category = {}

      @categories.each do |category|
        @total_articles_per_category[category.name] = category.total_articles
      end
    end
    def show
      # Display category details and associated articles
      # @articles = @category.articles
    end
    def new
      @category = Category.new
    end
    def create
      @category = Category.new(categories_params)
      if @category.save
        redirect_to categories_path
      else
        render :new, status: :unprocessable_entity
      end
    end
    def edit

    end
    def update
        @category = Category.find(params[:id])
        if @category.update(categories_params)
          redirect_to categories_path, notice: 'Category was successfully updated.'
        else
          render :edit
        end
      end
    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        
        redirect_to root_path, status: :see_other
    end
    # def destroy
    #   @category.destroy
    #   redirect_to category_articles_path(@category), notice: 'Category was successfully destroyed.'
    # end
    private
    def set_category
      @category = Category.find(params[:id])
    end
    def categories_params
      params.require(:category).permit(:name, :description)
    end
  end

    
  

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController


    def index
      @comments = Comment.where(article_id: params[:article_id])
      render json: @comments
    end

    # def show
    #   @category = Category.find(params[:category_id])
    #   @article = Article.find(params[:article_id])
  
    #   @comment = @article.comments(comments_params)
    # end

    def create
      @category = Category.find(params[:category_id])
      @article = Article.find(params[:article_id])
  
      @comment = @article.comments.create(comment_params)
  
      redirect_to category_article_path(@category, @article)
    end
  
    def destroy
      @category = Category.find(params[:category_id])
      @article = Article.find(params[:article_id])
  
      @comment = @article.comments.find(params[:id])
      
      @comment.destroy
      redirect_to category_article_path(@category, @article), status: :see_other
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
  end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)

    #charge the user's card (post request)
    charge = Stripe::Charge.create({
      amount: @donation.amount * 100, #convert to cents
      currency: 'usd',
      source: params[:stripe_token],
      description: 'Donation',
    })

    @donation.save

    flash[:success] = 'Thank you for your donation!'
    redirect_to root_path
  rescue Stripe::CardError => e
    flash[:error] = e.message
    render :new
  end

  private

  def donation_params
    params.require(:donation).permit(:firstname, :lastname, :email, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: [@category, @article] do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
    </div>

    <div class="field">
      <%= form.label :category_id %><br>
      <%= form.collection_select :category_id, Category.all, :id, :name, prompt: 'Select a category' %>
    </div>


    <div>
      <%= form.submit %>
    </div>
  <% end %>
  
  

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: 
@article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<h2>Most Recent Articles</h2>
<ul>
  <% @recent_articles.each do |article| %>
      <li>
        <%= link_to article.title, category_article_path(article.category, article) %>
      </li>
  <% end %>
</ul>


<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, category_article_path(article.category, article) %>
      </li>
      <% end %>
  <% end %>
</ul>

<%= link_to "New Article", new_category_article_path(@category) %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: 
@article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<p><strong>Category:</strong> <%= @article.category.name %></p>

<ul>
  <li><%= link_to "Edit", edit_category_article_path(@category, @article) %></li>
  <li><%= link_to "Delete", category_article_path(@category), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>
<ul>

<div class="comment-section">
  <h2>Comments</h2>
  <%= render @article.comments %>
  <div id="comments">
  </div>
</div>

<div id="category-id" data-category="<%= @category.id %>"> </div>
<button id="load-comments" data-article="<%= @article.id %>"> Load Comments </button>
 
  

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>

</div>

app/views/categories/_form.html.erb
<%= form_with model: [@category] do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% category.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% category.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/categories/edit.html.erb
<h1> Edit Category </h1>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<body>
    
    <header>
        <div class = "logo">
            <h1 class = "logo-text"><span>Bantu</span>Blogging</h1>
        </div>
    <ul>
        <% @categories.each do |category| %>
            <li><%= link_to category.name, category_path(category) %> </li>
        <% end %>
    </ul>
    </header>

    <div> Welcome <%= current_user.user_name %> </div
    <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
    <% unless user_signed_in? %>
    <%= button_to "Sign in", new_user_session_path %>
    <% end %>


    <div class = "sidebar">
        <div class = "section-categories">
            <h2 class = "section-title">Categories</h2>
            <ul>
            <% @categories.each do |category| %>
                <li><%= category.name %> has <%= category.articles.count %> articles and more to come! | <em><%= category.description %></em> </li>
            <% end %>
            </ul>
        </div>
    </div>


    <div class = "page-wrapper">
    </div>


    <div class = "footer">
        <div class = "footer-content">
            <div class = "footer-section" "about">
            <h1><span>Bantu</span>Blogging</h1>
            <p></p>
            </div>
            <div class = "contact">
            </div>
            <div class = "footer-section" "links">
                <h2>
                    Quick links
                </h2>
                <ul>
                    <li><%= link_to "Create New Category", new_category_path(@category) %> </li>
                </ul>
            </div>
            <div class = "footer-section" "contact-form">
                <h2>Contact us</h2>
            </div>
        </div>
        <div class = "footer-bottom">
            Bloggingbantu.com | Created by Kenyon Nyangai
        </div>
    </div>


</body>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p><%= @category.description %></p>


<ul>
  <li><%= link_to "Articles (#{@category.total_articles})", category_articles_path(@category, @articles) %></li> 
  <li><%= link_to "Edit", edit_category_path(@category) %></li>
  <li><%= link_to "Delete", category_path(@category), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %></li>
</ul>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>

<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
  <p>
  <%= link_to "Like Comment", category_article_comment_path
  <%= link_to "Delete Comment", category_article_comment_path(@category, @article, comment), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>
</p>

<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @category, @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <div= "comment body">
      <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
      </p>
    </div>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
    </div>


    <p>
      <%= form.submit %>
    </p>
  <% end %>
  

app/views/donations/create.html.erb
<h1>Donations#create</h1>
<p>Find me in app/views/donations/create.html.erb</p>

app/views/donations/new.html.erb
<h1>Make a Donation</h1>

<%= form_with(model: @donation, url: donations_path, method: 'post', local:true, id:'donation-form') do |form| %>
    
    <div class="field">
        <%= form.label :first_name %>
        <%= form.text_area :first_name %>
    </div>
    <div class="field">
        <%= form.label :last_name %>
        <%= form.text_area :last_name %>
    </div>
    <div class="field">
        <%= form.label :email %>
        <%= form.text_area :email %>
    </div>
    <div class="field">
        <%= form.label :amount %>
        <%= form.text_area :amount %>
    </div>

    <div id="card-container">
        <div id= "card-element" class="form-control">


        </div id= "card-errors" role="alert"></div>
    </div>

    <button id="donate-button" class="btn btn-primary"> donate </button>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Candal&family=Lora&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'donation.css' %>
    <%= stylesheet_link_tag 'style.css' %>

    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <%= javascript_include_tag 'https://js.stripe.com/v3/' %>
    <%= javascript_pack_tag 'application' %>
    
    
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>